# Generated by Django 4.2.7 on 2024-02-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'کالا', 'verbose_name_plural': 'کالاها'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'کالا سبد خرید', 'verbose_name_plural': 'کالاهای سبد خرید'},
        ),
    ]
