# Generated by Django 4.2.7 on 2024-03-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_variation_options'),
        ('carts', '0002_alter_cart_options_alter_cartitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation', verbose_name='واریانت ها'),
        ),
    ]
