# Generated by Django 5.0.2 on 2024-02-22 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(unique=True, verbose_name='آدرس دسته بندی')),
                ('description', models.TextField(max_length=255, verbose_name='توضیحات دسته بندی')),
                ('category_image', models.ImageField(blank=True, upload_to='images/category_images', verbose_name='تصویر دسته بندی')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, unique=True, verbose_name='نام محصول')),
                ('slug', models.SlugField(unique=True, verbose_name='آدرس محصول')),
                ('description', models.TextField(max_length=550, verbose_name='توضیحات کامل محصول')),
                ('information', models.CharField(max_length=255, verbose_name='توضیحات کوتاه')),
                ('concise', models.TextField(max_length=100, verbose_name='توضیح مختصر')),
                ('color', models.CharField(choices=[('ابی', 'ابی'), ('قرمز', 'قرمز'), ('زرد', 'زرد'), ('سیاه', 'سیاه'), ('سفید', 'سفید'), ('قهوه ای', 'قهوه ای')], max_length=50, verbose_name='رنگ')),
                ('size', models.CharField(choices=[('XL', 'XL'), ('S', 'S'), ('M', 'M'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=50, verbose_name='اندازه')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='قیمت')),
                ('image', models.ImageField(upload_to='images/product_images', verbose_name='عکس')),
                ('stock', models.IntegerField(default=0, verbose_name='موجودی')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تخفیف')),
                ('is_available', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
